package webui

import (
	"bytes"
	"strings"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

//go:generate go run ./gen/chromacss

const (
	chromaLightStyle = "github"
	chromaDarkStyle  = "github-dark"
)

// GenerateChromaCSS returns the combined, theme-scoped chroma stylesheet:
// light rules under :root, dark rules under :root[data-theme="dark"].
func GenerateChromaCSS() string {
	var b strings.Builder
	b.WriteString("/* generated by chromacss.go - run `go generate ./internal/adapter/webui/...` */\n")
	b.WriteString(scopedCSS(chromaLightStyle, ":root"))
	b.WriteString(scopedCSS(chromaDarkStyle, `:root[data-theme="dark"]`))
	return b.String()
}

func scopedCSS(styleName, scope string) string {
	s := styles.Get(styleName)
	f := chromahtml.New(chromahtml.WithClasses(true), chromahtml.ClassPrefix(""))
	var buf bytes.Buffer
	_ = f.WriteCSS(&buf, s)

	var scoped strings.Builder
	for _, line := range strings.Split(buf.String(), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			scoped.WriteString(line + "\n")
			continue
		}
		if strings.Contains(line, "{") {
			scoped.WriteString(scopeCSSRule(line, scope) + "\n")
			continue
		}
		scoped.WriteString(line + "\n")
	}
	return scoped.String()
}

func scopeCSSRule(line, scope string) string {
	trimmed := strings.TrimSpace(line)
	if strings.HasPrefix(trimmed, "/*") {
		if end := strings.Index(line, "*/"); end >= 0 {
			return line[:end+2] + " " + scope + " " + strings.TrimSpace(line[end+2:])
		}
	}
	return scope + " " + line
}
