issuer: http://DEX_ISSUER_PLACEHOLDER
storage:
  type: memory
web:
  http: 0.0.0.0:5556
oauth2:
  skipApprovalScreen: true
  responseTypes: ["code", "token", "id_token"]
staticClients:
  - id: flow-server
    redirectURIs:
      - 'http://localhost:8080/auth/callback'
    name: 'Flow Server'
    secret: flow-server-secret
  - id: flow-cli
    public: true
    name: 'Flow CLI'
enablePasswordDB: true
staticPasswords:
  - email: "alice@example.com"
    # bcrypt hash of "password"
    hash: "$2a$10$2b2cu2a5yhHRk6PEpvb8d.O4WXuOdQ8KW58SOOJq.fxvKPVqMjyy."
    username: "alice"
    userID: "alice-static-uid"
