package httpserver_test

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/serverkraken/flow/internal/adapter/httpserver"
	"github.com/serverkraken/flow/internal/adapter/sse"
	"github.com/serverkraken/flow/internal/domain"
	"github.com/serverkraken/flow/internal/ports"
	"github.com/serverkraken/flow/internal/testutil"
	"github.com/serverkraken/flow/internal/usecase"
)

func newStatsServer() (*httpserver.Server, *sse.Bus) {
	clk := testutil.FakeClock{T: time.Date(2026, 6, 15, 10, 0, 0, 0, time.UTC)}
	bus := sse.NewBus()
	settings := testutil.NewFakeUserSettingsStore()
	sessions := testutil.NewFakeSessionStore()
	dayOffs := testutil.NewFakeDayOffStore()
	listDayOffs := usecase.ListDayOffs{Store: dayOffs, Settings: settings, Loc: time.UTC}
	statsUC := usecase.StatsComputer{
		Sessions: sessions,
		Settings: settings,
		DayOffs:  listDayOffs,
		Clock:    clk,
		Loc:      time.UTC,
	}
	srv := &httpserver.Server{
		Verifier:  testutil.FakeVerifier{ID: ports.Identity{Subject: "sub-1", Username: "msoent"}},
		Ensure:    usecase.EnsureUser{Users: testutil.NewFakeUserStore(), IDs: &testutil.FakeIDGen{}, Allow: func(ports.Identity) bool { return true }},
		Bus:       bus,
		Clock:     clk,
		Stats:     statsUC,
		SetTarget: usecase.SetTargetConfig{Settings: settings},
	}
	return srv, bus
}

func TestHandleStats_InvalidRange(t *testing.T) {
	srv, _ := newStatsServer()
	ts := httptest.NewServer(srv.Routes())
	defer ts.Close()

	req, _ := http.NewRequest("GET", ts.URL+"/api/v1/stats?range=year", nil)
	req.Header.Set("Authorization", "Bearer x")
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	_ = res.Body.Close()
	if res.StatusCode != http.StatusBadRequest {
		t.Fatalf("want 400 for invalid range, got %d", res.StatusCode)
	}
}

func TestHandleWeek_BadRef(t *testing.T) {
	srv, _ := newStatsServer()
	ts := httptest.NewServer(srv.Routes())
	defer ts.Close()

	req, _ := http.NewRequest("GET", ts.URL+"/api/v1/week?ref=not-a-date", nil)
	req.Header.Set("Authorization", "Bearer x")
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	_ = res.Body.Close()
	if res.StatusCode != http.StatusBadRequest {
		t.Fatalf("want 400 for malformed ref, got %d", res.StatusCode)
	}
}

func TestHandleSetTarget_PublishesEvent(t *testing.T) {
	srv, bus := newStatsServer()
	ts := httptest.NewServer(srv.Routes())
	defer ts.Close()

	// Subscribe before the request to capture the published event.
	// We need the user ID — EnsureUser creates it lazily. Prime a request first.
	primeReq, _ := http.NewRequest("GET", ts.URL+"/api/v1/stats?range=week", nil)
	primeReq.Header.Set("Authorization", "Bearer x")
	primeRes, _ := http.DefaultClient.Do(primeReq)
	_ = primeRes.Body.Close()

	// Now subscribe. The user ID generated by FakeIDGen for sub-1 is "id-1".
	ch, cancel := bus.Subscribe("id-1")
	defer cancel()

	body := `{"defaultTargetMin":480,"weekdayTargetMin":{"5":360}}`
	req, _ := http.NewRequest("POST", ts.URL+"/api/v1/settings/target", strings.NewReader(body))
	req.Header.Set("Authorization", "Bearer x")
	req.Header.Set("Content-Type", "application/json")
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	_ = res.Body.Close()
	if res.StatusCode != http.StatusNoContent {
		t.Fatalf("want 204, got %d", res.StatusCode)
	}

	// Drain the channel — expect settings.changed.
	select {
	case ev := <-ch:
		if ev.Type != domain.EventSettingsChanged {
			t.Fatalf("want settings.changed event, got %q", ev.Type)
		}
	default:
		t.Fatal("no event published after POST /api/v1/settings/target")
	}
}

func TestHandleSetTarget_BadWeekdayKey(t *testing.T) {
	srv, _ := newStatsServer()
	ts := httptest.NewServer(srv.Routes())
	defer ts.Close()

	body := `{"defaultTargetMin":480,"weekdayTargetMin":{"9":60}}`
	req, _ := http.NewRequest("POST", ts.URL+"/api/v1/settings/target", strings.NewReader(body))
	req.Header.Set("Authorization", "Bearer x")
	req.Header.Set("Content-Type", "application/json")
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	_ = res.Body.Close()
	if res.StatusCode != http.StatusBadRequest {
		t.Fatalf("want 400 for weekday key 9, got %d", res.StatusCode)
	}
}
